Raise minimum tested version to rustc 1.34.0
Required by the byteorder dev-dependency.

    error[E0277]: the trait bound `[u8; 2]: std::convert::From<&[u8]>` is not satisfied
        --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.4.2/src/lib.rs:1959:37
         |
    1959 |         u16::from_be_bytes(buf[..2].try_into().unwrap())
         |                                     ^^^^^^^^ the trait `std::convert::From<&[u8]>` is not implemented for `[u8; 2]`
         |
         = note: required because of the requirements on the impl of `std::convert::TryFrom<&[u8]>` for `[u8; 2]`
         = note: required because of the requirements on the impl of `std::convert::TryInto<[u8; 2]>` for `&[u8]`